<link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>/css/uploadifive.css">
<button type="button" class="btn btn-sm btn-primary js_addbanner" data-toggle="modal" data-target="#addModal" style="margin-bottom:10px;">新增</button>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>
<nav style="float:right;">
    <ul class="pagination js_page"></ul>
</nav>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">编辑</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="id" class="col-sm-4 control-label">编号</label>
                        <div class="col-sm-8">
                            <p class="form-control-static js_id"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">链接（en）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_url_en" placeholder="链接（en）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">链接（tc）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_url_tc" placeholder="链接（tc）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="photo" class="col-sm-4 control-label">图片
                            <button type="button" class="btn btn-primary js_upload" data-toggle="modal" data-target="#uploadModal"><span class="glyphicon glyphicon-plus"></span></button></label>
                        <div class="col-sm-8">
                            <img class="img-responsive js_photo_prev img-thumbnail" style="width:120px; height: 60px;">
                            <input type="hidden" class="form-control js_photo" placeholder="将要修改的图片url粘贴到这里，留空表示不需要修改图片">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="aorder" class="col-sm-4 control-label">排序（数字越大越靠前）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_sort" placeholder="排序（数字越大越靠前）">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 点击保存前请检查信息无误，如有需要请先备份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">新增</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">链接（en）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_url_en" placeholder="链接（en）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">链接（tc）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_url_tc" placeholder="链接（tc）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="photo" class="col-sm-4 control-label">图片
                            <button type="button" class="btn btn-primary js_add_upload" data-toggle="modal" data-target="#uploadModal"><span class="glyphicon glyphicon-plus"></span></button></label>
                        <div class="col-sm-8">
                            <img class="img-responsive js_add_photo_prev img-thumbnail" style="width:120px; height: 60px;">
                            <input type="hidden" class="form-control js_add_photo" placeholder="将要修改的图片url粘贴到这里，留空表示不需要修改图片">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="aorder" class="col-sm-4 control-label">排序（数字越大越靠前）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_sort" value="5">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 点击保存前请检查信息无误，如有需要请先备份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_add_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="uploadModal" tabindex="1" role="dialog" aria-labelledby="uploadModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">图片上传</h4>
            </div>
            <div class="modal-body">
                <input id="photo" type="file" multiple="false" value="" />
                <div>
                    <img src="" id="prevArea" style="max-width: 100px; max-height: 100px; ">
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary js_addPhoto">确定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="modal fade" id="confirmModal" tabindex="2" role="dialog" aria-labelledby="confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                温馨提示
            </div>
            <div class="modal-body">
                确定要删除该条数据？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary js_sure_delete">确定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>js/system/banner.js"></script>
