<link rel="stylesheet" href="<?php echo $resource_url; ?>css/uploadifive.css">
<link rel="stylesheet" href="<?php echo $resource_url; ?>libs/summernote/summernote.css">
<link rel="stylesheet" href="<?php echo $resource_url; ?>css/bootstrap-datetimepicker.min.css">

<style type="text/css">
    .prev-pic,.prev-pic2 {
        max-width: 400px;
        max-height: 300px;
        display: block;
        margin: 20px;
        border: 1px solid #ccc;
        padding: 10px;
    }
    .prev-frame,.prev-frame2 {
        display: inline-block;
        position: relative;
    }
    .prev-frame em,.prev-frame2 em {
        position: absolute;
        right: 25px;
        top: 20px;
        background: red;
        display: inline-block;
        width: 20px;
        height: 20px;
        text-align: center;
        color: #fff;
        font-weight: 1000;
        cursor: pointer;
    }
</style>

<div class="form-group">
    <label for="title">标题（en）</label>
    <input type="text" class="form-control" id="title_en" placeholder="请输入标题（en）">
</div>
<div class="form-group">
    <label for="title">标题（tc）</label>
    <input type="text" class="form-control" id="title_tc" placeholder="请输入标题（tc）">
</div>
<div class="form-group">
    <label for="clazz_id">分类</label>
    <select class="form-control" id="clazz_id"></select>
</div>
<div class="form-group">
    <label for="cover">封面圖</label>
    <input id="cover" type="file" multiple="false" value="" />
    <div class="js_coverPrevArea"></div>
</div>
<div class="form-group media_show">
    <label for="pic">圖片（媒體報導）</label>
    <input id="pic" type="file" multiple="false" value="" />
    <div>
        <img src="" id="prevArea" style="max-width: 100px; max-height: 100px; ">
    </div>
</div>
<div class="form-group press_show">
    <label for="pic2">相冊（新聞稿及相冊）</label>
    <input id="pic2" type="file" multiple="true" value="" />
    <div class="js_picPrevArea"></div>
</div>

<div class="form-group press_show">
    <label for="content_en">正文内容（en）</label>
    <div id="content_en"></div>
</div>
<div class="form-group press_show">
    <label for="content_tc">正文内容（tc）</label>
    <div id="content_tc"></div>
</div>
<div class="form-group press_show">
    <label for="pdf">pdf(英文)</label>
    <a href="" target="_blank" class="js_pdf_prev" style="margin-left: 20px;"></a>
    <input type="file" value="" multiple="false" id="js_upload_btn01">
    <input type="hidden" class="js_pdf" value="">
</div>

<div class="form-group">
    <label for="pdf2">pdf</label>
    <a href="" target="_blank" class="js_pdf_prev2" style="margin-left: 20px;"></a>
    <input type="file" value="" multiple="false" id="js_upload_btn02">
    <input type="hidden" class="js_pdf2" value="">
</div>
<div class="form-group media_show">
    <label for="author_en">作者(英文)</label>
    <input type="text" class="form-control" id="author_en" placeholder="请输入作者(英文)">
</div>
<div class="form-group media_show">
    <label for="author_tc">作者(中文)</label>
    <input type="text" class="form-control" id="author_tc" placeholder="请输入作者(中文)">
</div>
<div class="form-group">
    <label for="date">date</label>
    <div class="input-group date">
      <input type="text" class="form-control"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
    </div>
</div>

<input type="hidden" name="nid" value="<?php echo $nid; ?>" class="js_nid">
<input type="hidden" class="js_add_clazz_id" value="add">

<button type="submit" class="btn btn-primary js_submit">保存</button>

<script src="<?php echo $resource_url; ?>js/bootstrap-datepicker.min.js" charset="utf-8"></script>
<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/summernote.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/lang/summernote-zh-CN.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/lang/summernote-zh-TW.js"></script>
<script src="<?php echo $resource_url; ?>js/system/content_add.js"></script>

<script type="text/javascript">
    $('.input-group.date').datepicker({
    });
    $(function() {
        $('#js_upload_btn01').uploadifive({
            fileType: 'application/pdf',
            multi: false,
            removeCompleted: false,
            buttonText: '上传PDF',
            fileSizeLimit: '100MB',
            method: 'post',
            buttonClass: 'signup-upload-file',
            fileObjName: 'uploadfile',
            uploadScript: config.apiServer + 'content/post',
            formData: {
                'actionxm': 'uploadPdf'
            },
            onUploadComplete: function(file, data, response) {
                var result = $.parseJSON(data);
                if(result['status']==0) {
                    $('.js_pdf').val(result['name']);
                    $('.js_pdf_prev').attr('href', result['name']);
                    $('.js_pdf_prev').html(result['name']+'<em class="js_delete_pdf">x</em>');
                }
            },
            onError: function(errorType) {
                alert('The error was: ' + errorType);
            }
        });
        $('#js_upload_btn02').uploadifive({
            fileType: 'application/pdf',
            multi: false,
            removeCompleted: false,
            buttonText: '上传PDF',
            fileSizeLimit: '100MB',
            method: 'post',
            buttonClass: 'signup-upload-file',
            fileObjName: 'uploadfile',
            uploadScript: config.apiServer + 'content/post',
            formData: {
                'actionxm': 'uploadPdf'
            },
            onUploadComplete: function(file, data, response) {
                var result = $.parseJSON(data);
                if(result['status']==0) {
                    $('.js_pdf2').val(result['name']);
                    $('.js_pdf_prev2').attr('href', result['name']);
                    $('.js_pdf_prev2').html(result['name']+'<em class="js_delete_pdf2">x</em>');
                }
            },
            onError: function(errorType) {
                alert('The error was: ' + errorType);
            }
        });
    })
</script>
