<link rel="stylesheet" href="<?php echo $resource_url; ?>css/uploadifive.css">
<link rel="stylesheet" href="<?php echo $resource_url; ?>libs/summernote/summernote.css">
<link rel="stylesheet" href="<?php echo $resource_url; ?>css/bootstrap-datetimepicker.min.css">
<style media="screen">
.js_delete_pdf,.js_delete_pdf2 {
   position: relative;
   left: 10px;
   top: 0px;
   background: red;
   display: inline-block;
   width: 20px;
   height: 20px;
   text-align: center;
   color: #fff;
   font-weight: 1000;
   cursor: pointer;
}
.prev-pic,.prev-pic2 {
    max-width: 400px;
    max-height: 300px;
    display: block;
    margin: 20px;
    border: 1px solid #ccc;
    padding: 10px;
}
.prev-frame,.prev-frame2 {
    display: inline-block;
    position: relative;
}
.prev-frame em,.prev-frame2 em {
    position: absolute;
    right: 25px;
    top: 20px;
    background: red;
    display: inline-block;
    width: 20px;
    height: 20px;
    text-align: center;
    color: #fff;
    font-weight: 1000;
    cursor: pointer;
}

</style>
<div class="form-group">
    <label for="title">标题（en）</label>
    <input type="text" class="form-control" id="title_en" placeholder="请输入标题（en）" value="<?php echo $info['title_en']; ?>">
</div>
<div class="form-group">
    <label for="title">标题（tc）</label>
    <input type="text" class="form-control" id="title_tc" placeholder="请输入标题（tc）"  value="<?php echo $info['title_tc']; ?>">
</div>
<div class="form-group">
    <label for="clazz_id">分类</label>
    <select class="form-control" id="clazz_id"></select>
</div>
<div class="form-group">
    <label for="cover">封面圖</label>
    <input id="cover" type="file" multiple="false" value="" />
    <div class="js_coverPrevArea"></div>
</div>
<div class="form-group media_show" >
    <label for="pic">圖片（媒體報導）</label>
    <input id="pic" type="file" multiple="false" value="" />
    <div>
        <?php if(strpos($info['pic'],',')): ?>
            <img src="<?php echo strstr($info['pic'], ',', TRUE) ?>" alt="" id="prevArea" style="max-width: 100px; max-height: 100px; ">
        <?php else: ?>
            <img src="<?php echo $info['pic'] ?>" alt="" id="prevArea" style="max-width: 100px; max-height: 100px; ">
        <?php endif; ?>
    </div>

</div>
<div class="form-group press_show">
    <label for="pic2">相冊（新聞稿及相冊）</label>
    <input id="pic2" type="file" multiple="true" value="" />
    <div class="js_picPrevArea"></div>
</div>
<!-- <div class="form-group">
    <label for="descript_en">描述（en）</label>
    <textarea class="form-control" id="descript_en"><?php echo $info['descript_en']; ?></textarea>
</div>
<div class="form-group">
    <label for="descript_tc">描述（tc）</label>
    <textarea class="form-control" id="descript_tc"><?php echo $info['descript_tc']; ?></textarea>
</div> -->
<div class="form-group press_show">
    <label for="content_en">正文内容（en）</label>
    <div id="content_en"></div>
</div>
<div class="form-group press_show">
    <label for="content_tc">正文内容（tc）</label>
    <div id="content_tc"></div>
</div>
<div class="form-group press_show">
    <label for="pdf">pdf(英文)</label>
    <a href="<?php echo $info['pdf_en']; ?>" target="_blank" class="js_pdf_prev" style="margin-left: 20px;"><?php echo $info['pdf_en']; ?></a><?php if($info['pdf_en']):?><em class="js_delete_pdf">x</em><?php endif;?>
    <input type="file" value="" multiple="false" id="js_upload_btn01">
    <input type="hidden" class="js_pdf" value="<?php echo $info['pdf_en']; ?>">
</div>
<div class="form-group">
    <label for="pdf2">pdf</label>
    <a href="<?php echo $info['pdf_tc']; ?>" target="_blank" class="js_pdf_prev2" style="margin-left: 20px;"><?php echo $info['pdf_tc']; ?></a><?php if($info['pdf_tc']):?><em class="js_delete_pdf2">x</em><?php endif;?>
    <input type="file" value="" multiple="false" id="js_upload_btn02">
    <input type="hidden" class="js_pdf2" value="<?php echo $info['pdf_tc']; ?>">
</div>
<div class="form-group media_show">
    <label for="author">作者(英文)</label>
    <input type="text" class="form-control" id="author_en" placeholder="请输入作者(英文)" value="<?php echo $info['author_en']; ?>">
</div>
<div class="form-group media_show">
    <label for="author">作者(中文)</label>
    <input type="text" class="form-control" id="author_tc" placeholder="请输入作者(中文)" value="<?php echo $info['author_tc']; ?>">
</div>
<div class="form-group">
    <label for="date">date</label>
    <div class="input-group date">
      <input type="text" class="form-control" value="<?php echo date('m/d/Y', $info['create_time']) ?>"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
    </div>
</div>

<textarea class="js_pContent_en" style="display: none;"><?php echo $info['content_en']; ?></textarea>
<textarea class="js_pContent_tc" style="display: none;"><?php echo $info['content_tc']; ?></textarea>
<input type="hidden" class="js_update_clazz_id" value="<?php echo $info['clazz_id']; ?>">

<input type="hidden" name="nid" value="<?php echo $nid; ?>" class="js_nid">
<input type="hidden" class="js_update_pic" value='<?php echo $info['pic']; ?>'>
<input type="hidden" class="js_update_cover" value='<?php echo $info['cover']; ?>'>

<button type="submit" class="btn btn-primary js_submit">保存</button>

<script src="<?php echo $resource_url; ?>js/bootstrap-datepicker.min.js" charset="utf-8"></script>
<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/summernote.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/lang/summernote-zh-CN.js"></script>
<script src="<?php echo $resource_url; ?>js/system/content_add.js"></script>
<script type="text/javascript">
    $('.input-group.date').datepicker({
    });
    $(function() {

        $('#content_en').summernote('code', $('.js_pContent_en').val());
        $('#content_tc').summernote('code', $('.js_pContent_tc').val());

        $('#js_upload_btn01').uploadifive({
            fileType: 'application/pdf',
            multi: false,
            removeCompleted: false,
            buttonText: '上传PDF',
            fileSizeLimit: '100MB',
            method: 'post',
            buttonClass: 'signup-upload-file',
            fileObjName: 'uploadfile',
            uploadScript: config.apiServer + 'content/post',
            formData: {
                'actionxm': 'uploadPdf'
            },
            onUploadComplete: function(file, data, response) {
                var result = $.parseJSON(data);
                if(result['status']==0) {
                    $('.js_pdf').val(result['name']);
                    $('.js_pdf_prev').attr('href', result['name']);
                    $('.js_pdf_prev').html(result['name']);
                    $('.js_pdf_prev').after('<em class="js_delete_pdf">x</em>')
                }
            },
            onError: function(errorType) {
                alert('The error was: ' + errorType);
            }
        });

        $('#js_upload_btn02').uploadifive({
            fileType: 'application/pdf',
            multi: false,
            removeCompleted: false,
            buttonText: '上传PDF',
            fileSizeLimit: '100MB',
            method: 'post',
            buttonClass: 'signup-upload-file',
            fileObjName: 'uploadfile',
            uploadScript: config.apiServer + 'content/post',
            formData: {
                'actionxm': 'uploadPdf'
            },
            onUploadComplete: function(file, data, response) {
                var result = $.parseJSON(data);
                if(result['status']==0) {
                    $('.js_pdf2').val(result['name']);
                    $('.js_pdf2_prev').attr('href', result['name']);
                    $('.js_pdf2_prev').html(result['name']);
                    $('.js_pdf2_prev').after('<em class="js_delete_pdf2">x</em>')
                }
            },
            onError: function(errorType) {
                alert('The error was: ' + errorType);
            }
        });
    })
</script>
