<!DOCTYPE html>
<html lang="zh-CN">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
        <meta name="description" content="">
        <meta name="author" content="">

        <title>内容管理系统</title>

        <!-- Bootstrap core CSS -->
        <link href="<?php echo $resource_url; ?>css/bootstrap.min.css" rel="stylesheet">

        <!-- Custom styles for this template -->
        <link href="<?php echo $resource_url; ?>/css/signin.css" rel="stylesheet">

        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
        <!--[if lt IE 9]><script src="<?php echo $resource_url; ?>js/ie8-responsive-file-warning.js"></script><![endif]-->
        <script src="<?php echo $resource_url; ?>js/ie-emulation-modes-warning.js"></script>
        <script src="<?php echo $resource_url; ?>js/jquery.min.js"></script>
        <script src="<?php echo $resource_url; ?>js/common.js"></script>

        <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
        <!--[if lt IE 9]>
          <script src="<?php echo $resource_url; ?>js/html5shiv.min.js"></script>
          <script src="<?php echo $resource_url; ?>js/respond.min.js"></script>
        <![endif]-->
    </head>

    <body>

        <div class="container">

            <form class="form-signin js_form">
                <h2 class="form-signin-heading" style="text-align: center; margin-bottom: 30px;">内容管理系统</h2>
                <label for="inputUsername" class="sr-only">用户名</label>
                <input type="text" id="inputUsername" class="form-control" placeholder="用户名" required autofocus>
                <label for="inputPassword" class="sr-only">密码</label>
                <input type="password" id="inputPassword" class="form-control" placeholder="密码" required>
                <!-- <div class="checkbox">
                    <label>
                        <input type="checkbox" value="remember-me"> Remember me
                    </label>
                </div> -->
                <button class="btn btn-lg btn-primary btn-block js_login" type="submit">登  录</button>
                <div class="alert alert-success" style="display:none;" role="alert">...</div>
                <div class="alert alert-info" style="display:none;" role="alert">...</div>
                <div class="alert alert-warning" style="display:none;" role="alert">...</div>
                <div class="alert alert-danger" style="display:none;" role="alert">...</div>
            </form>

        </div> <!-- /container -->

        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="<?php echo $resource_url; ?>js/ie10-viewport-bug-workaround.js"></script>

        <script type="text/javascript">
            $(function() {
                var page = {
                    // 请求数据公用方法
                    requestData: function(json) {
                        $.ajax({
                            url: json.api,
                            type: json.type,
                            dataType: 'json',
                            data: json.data,
                            timeout: 30000,
                            success: function(data) {
                                json.callback(data);
                            },
                            error: function(xhr, errorType, error) {
                                if(!navigator.onLine || errorType==='timeout') {
                                    alert('网络连接有问题，请检查网络');
                                } else {
                                    alert(xhr.response);
                                }
                            }
                        })
                    },
                    // 登录
                    login: function() {
                        $('.js_login').attr('disabled', true);
                        var username = $('#inputUsername').val(),
                            password = $('#inputPassword').val(),
                            json = {
                                api: config.apiServer + 'login/post',
                                type: 'post',
                                data: {
                                    actionxm: 'login',
                                    username: username,
                                    password: password
                                }
                            };
                        var callback = function(res) {
                            console.log(res);
                            if(res.status==0) {
                                $('.alert-success').text(res.msg).show();
                                setTimeout("window.location.href = '/adm/index'", 1000);
                            } else {
                                $('.js_login').attr('disabled', false);
                                $('.alert-danger').text(res.msg).show();
                                setTimeout("$('.alert').hide()", 3000);
                            }
                        };
                        var errorCall = function() {
                            $('.js_login').attr('disabled', false);
                            $('.alert-warning').text('系统繁忙，请稍后再试').show();
                            setTimeout("$('.alert').hide()", 3000);
                        };
                        json.callback = callback;
                        json.errorCall = errorCall;
                        page.requestData(json);
                    }
                };
                $('.js_form').submit(function(e) {
                    e.preventDefault();
                    page.login();
                });
            });
        </script>
    </body>
</html>
