<button type="button" class="btn btn-sm btn-primary js_addbanner" data-toggle="modal" data-target="#addModal" style="margin-bottom:10px;">新增</button>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>

<!-- 新增菜单弹窗 -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">新增</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="name" class="col-sm-4 control-label">菜單標題</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_name" id="name" placeholder="菜单标题">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ctrl_name" class="col-sm-4 control-label">控制器</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_ctrl_name" id="ctrl_name" placeholder="控制器">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="menuTree" class="col-sm-4 control-label">上級菜單</label>
                        <div class="col-sm-8">
                            <select class="form-control js_add_menuTree">
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="sort" class="col-sm-4 control-label">排序（數字越大越靠前）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_sort" id="sort" placeholder="排序（数字越大越靠前）" value="5">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="mark" class="col-sm-4 control-label">標誌</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_mark" id="ctrl_name" placeholder="标志">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 點擊保存前请檢查信息無誤，如有需要請先備份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_add_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- 编辑菜单弹窗 -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">編輯</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <input type="hidden" class="js_update_id">
                    <div class="form-group">
                        <label for="name" class="col-sm-4 control-label">菜單標題</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_name" placeholder="菜單標題">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="ctrl_name" class="col-sm-4 control-label">控制器</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_ctrl_name" placeholder="控制器">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="menuTree" class="col-sm-4 control-label">上級菜單</label>
                        <div class="col-sm-8">
                            <select class="form-control js_update_menuTree">
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="sort" class="col-sm-4 control-label">排序（數字越大越靠前）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_sort" placeholder="排序（數字越大越靠前）" value="5">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="mark" class="col-sm-4 control-label">標誌</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_mark" placeholder="標誌">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 點擊保存前请檢查信息無誤，如有需要請先備份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- 确认删除弹窗 -->
<div class="modal fade" id="confirmModal" tabindex="2" role="dialog" aria-labelledby="confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                溫馨提示
            </div>
            <div class="modal-body">
                確定要刪除該條數據？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary js_sure_delete">確定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<script src="<?php echo $resource_url; ?>js/system/menu_index.js"></script>
