<link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>/css/uploadifive.css">
<button type="button" class="btn btn-sm btn-primary js_addbanner" data-toggle="modal" data-target="#addModal" style="margin-bottom:10px;">新增</button>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>
<nav style="float:right;">
    <ul class="pagination js_page"></ul>
</nav>

<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">編輯</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="id" class="col-sm-4 control-label">編號</label>
                        <div class="col-sm-8">
                            <p class="form-control-static js_id"></p>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">內容（en）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_content_en" placeholder="请输入內容（en）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">內容（tc）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_content_tc" placeholder="请输入內容（tc）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">鏈接（en）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_url_en" placeholder="请输入鏈接（en）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">鏈接（tc）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_url_tc" placeholder="请输入鏈接（tc）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="aorder" class="col-sm-4 control-label">排序（數字越大越靠前）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_sort" placeholder="排序（數字越大越靠前）">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 點擊保存前请檢查信息無誤，如有需要請先備份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">新增</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">內容（en）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_content_en" placeholder="请输入內容（en）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">內容（tc）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_content_tc" placeholder="请输入內容（tc）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">鏈接（en）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_url_en" placeholder="请输入鏈接（en）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="url" class="col-sm-4 control-label">鏈接（tc）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_url_tc" placeholder="请输入鏈接（tc）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="aorder" class="col-sm-4 control-label">排序（數字越大越靠前）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_sort" value="5">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 點擊保存前请檢查信息無誤，如有需要請先備份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_add_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmModal" tabindex="2" role="dialog" aria-labelledby="confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                溫馨提示
            </div>
            <div class="modal-body">
                確定要刪除該條數據？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary js_sure_delete">確定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->


<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>js/system/notice.js"></script>
