<style>
.signup-upload-file{
    position: absolute!important;
    top: 330px;
    left: 46px;
    border-radius: 3.5px;
}
.add-upload-file{
    position: relative;
    top: -60px;
    left: 475px;
    border-radius: 3.5px;
}
.js_picPrevArea{
    display: none;
}
.js_str{
    width: 100%;
    display: inline-block;
    word-wrap: break-word;
}
#download{
    position: absolute;
    top: 336px;
    left: 200px;
}
</style>
<div class="well well-sm">
    <form class="form-inline js_searchFrom">
        <div class="form-group">
            <label for="title">標題</label>
            <input type="text" class="form-control" id="title" placeholder="输入查询的标题">
        </div>
        <button type="submit" class="btn btn-primary">搜索</button>
        |
        <button type="button" class="btn btn-success js_addContent"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>新建</button>
        <!-- <button type="button" class="btn btn-success js_addExl"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>导入EXEL</button> -->
    </form>
</div>
<!-- <input type="file" value="" multiple="false" id="js_addImgs" style="display:none"> -->
<!-- <div class="js_picPrevArea" style="display:none"></div> -->
<!-- 模态框（Modal） -->
<button class="btn btn-primary btn-sm" onclick="window.open('/public/download/instruction.pdf')">批量導入說明</button>&nbsp&nbsp&nbsp
<button class="btn btn-primary btn-sm" onclick="window.open('/public/download/example.xls')">下載excel示例</button><br><br>

<div class="well well-sm" style="height:161px">
    <form class="form-inline js_searchFrom2">
        <div class="form-group">
            <label for="title">選擇分類</label>
            <!-- <div class="col-sm-8"> -->
                <select class="form-control js_add_menuTree" >

                    <option value="0">/</option>
                    <?php foreach ($pic_clazz as $list): ?>
                    <?php
                    $prefix = '';
                    while($list['level'] >= 0) {
                        $prefix .= '|--';
                        $list['level']--;
                    };
                    ?>
                    <?php if(strlen($prefix)>3):?>
                        <option value="<?=$list['id']?>"><?=$prefix?><?=$list['name_en']?>(<?=$list['name_tc']?>)</option>
                    <?php else: ?>
                        <option disabled="disabled" value="<?=$list['id']?>"><?=$prefix?><?=$list['name_en']?>(<?=$list['name_tc']?>)</option>
                    <?php endif;?>
                    <?php endforeach ?>
                </select>
                <br><br>
            <!-- </div> -->
            <!-- <div class="col-sm-8"> -->
                <label for="dir">設置圖片集目錄</label>
                <input type="text" class="form-control" id="dir" placeholder="">
            <!-- </div> -->
        </div>
        <!-- <button type="submit" class="btn btn-primary">搜索</button>
        |
        <button type="button" class="btn btn-success js_addContent"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>新建</button> -->
        <!-- <button type="button" class="btn btn-success js_addExl"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span>导入EXEL</button> -->
    </form>
</div>
<!-- <input type="file" value="" multiple="false" id="js_addExl" style="display:none"> -->
<input type="file" name="js_addExl" id="js_addExl" /><br />

<div class="table-responsive" >
    <table class="table table-striped table-hover js_table">
    </table>
</div>
<nav style="float:right;">
    <ul class="pagination js_page"></ul>
</nav>

<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>js/system/pic_content.js"></script>
<script type="text/javascript">
    $(function() {
        var n = 1;
        $('#js_addImgs').uploadifive({
            removeCompleted: true,
            fileTypeDesc: '上传文件',
            fileTypeExts: '*.jpg;*.jpeg;*.gif;*.png',
            multi: true,
            buttonText: '批量上传图片',
            height: '25',
            width: '100',
            method: 'post',
            fileObjName: 'uploadfile',
            buttonClass: 'add-upload-file',
            uploadScript: config.apiServer + 'pic_content/post',
            formData: {
                'actionxm': 'upload_photo'
            },
            onUploadComplete: function(file, data, response) {
                result = $.parseJSON(data);
                if(result['status']==0) {
                    var html = result['name']+',';
                    $('.js_picPrevArea').append(html);
                } else {
                    alert(result['msg']);
                }
            },
            onQueueComplete: function(file, data, response) {
                function addP(){
                    var str = $('.js_picPrevArea').html();
                    str = str.substr(0,str.length-1);
                    var str2 = '<div class="js_str js_str'+n+'"></div>';
                    $('.js_picPrevArea').after(str2);
                    $('.js_str'+n).html(str);
                    $('.js_picPrevArea').html('');
                    n++;
                }
                addP();
            }
        });

        // $('body').delegate('.js_delete_pic', 'click', function(e) {
        //     $(e.currentTarget).parent().parent().remove();
        // });

    })
</script>
