<link rel="stylesheet" href="<?php echo $resource_url; ?>css/uploadifive.css">
<link rel="stylesheet" href="<?php echo $resource_url; ?>css/bootstrap-datetimepicker.min.css">

<button type="button" class="btn btn-sm btn-primary js_addbanner" data-toggle="modal" data-target="#addModal" style="margin-bottom:10px;">新增</button>
<div class="table-responsive">
    <table class="table table-striped table-hover js_table">
    </table>
</div>

<!-- 新增菜單弹窗 -->
<div class="modal fade" id="addModal" tabindex="-1" role="dialog" aria-labelledby="addModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">新增</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <div class="form-group">
                        <label for="name" class="col-sm-4 control-label"><span class="required">*</span>分類名稱（en）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_name_en" placeholder="分類名稱（en）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-sm-4 control-label"><span class="required">*</span>分類名稱（tc）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_name_tc" placeholder="分類名稱（tc）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="menuTree" class="col-sm-4 control-label"><span class="required">*</span>上級菜單</label>
                        <div class="col-sm-8">
                            <select class="form-control js_add_menuTree">
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pdf" class="col-sm-4 control-label"><a href="" target="_blank" class="js_pdf_prev" style="margin-right: 20px;"></a>pdf</label>
                        <div class="col-sm-8">
                            <input type="file" value="" multiple="false" id="js_upload_btn01">
                            <input type="hidden" class="js_pdf" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="date" class="col-sm-4 control-label">date</label>
                        <div class="input-group col-sm-8 date">
                          <input type="text" class="form-control js_add_date"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="sort" class="col-sm-4 control-label">排序（數字越大越靠前）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_add_sort" id="sort" placeholder="排序（數字越大越靠前）" value="5">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 點擊保存前請檢查信息無誤，如有需要請先備份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_add_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<!-- 編輯菜單弹窗 -->
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="editModal">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">編輯</h4>
            </div>
            <div class="modal-body">
                <form class="form-horizontal">
                    <input type="hidden" class="js_update_id">
                    <div class="form-group">
                        <label for="name" class="col-sm-4 control-label"><span class="required">*</span>分類名稱（en）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_name_en" placeholder="分類名稱（en）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="name" class="col-sm-4 control-label"><span class="required">*</span>分類名稱（tc）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_name_tc" placeholder="分類名稱（tc）">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="menuTree" class="col-sm-4 control-label"><span class="required">*</span>上級菜單</label>
                        <div class="col-sm-8">
                            <select class="form-control js_update_menuTree">
                            </select>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="pdf" class="col-sm-4 control-label"><a href="" target="_blank" class="js_pdf_update_prev" style="margin-right: 20px;"></a>pdf</label>
                        <div class="col-sm-8">
                            <input type="file" value="" multiple="false" id="js_upload_btn02">
                            <input type="hidden" class="js_update_pdf" value="">
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="date" class="col-sm-4 control-label">date</label>
                        <div class="input-group date col-sm-8">
                          <input type="text" class="form-control js_update_date"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="sort" class="col-sm-4 control-label">排序（數字越大越靠前）</label>
                        <div class="col-sm-8">
                            <input type="text" class="form-control js_update_sort" id="sort" placeholder="排序（數字越大越靠前）" value="5">
                        </div>
                    </div>
                    <div class="alert alert-warning alert-dismissible fade in" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <strong>Warning: </strong> 點擊保存前請檢查信息無誤，如有需要請先備份！
                    </div>
                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary js_saveBtn">Save changes</button>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="confirmModal" tabindex="2" role="dialog" aria-labelledby="confirmModal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                溫馨提示
            </div>
            <div class="modal-body">
                確定要刪除該條數據？
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                <button type="button" class="btn btn-primary js_sure_delete">確定</button>
            </div>
        </div><!-- /.modal-content -->
    </div><!-- /.modal-dialog -->
</div><!-- /.modal -->
<script src="<?php echo $resource_url; ?>js/bootstrap-datepicker.min.js" charset="utf-8"></script>
<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>js/system/pic_clazz.js"></script>

<script type="text/javascript">
    $(function() {
        $('.input-group.date').datepicker({
        });
        $('#js_upload_btn01').uploadifive({
            fileType: 'application/pdf',
            multi: false,
            removeCompleted: false,
            buttonText: '上传PDF',
            fileSizeLimit: '100MB',
            method: 'post',
            buttonClass: 'signup-upload-file',
            fileObjName: 'uploadfile',
            uploadScript: config.apiServer + 'pic_clazz/post',
            formData: {
                'actionxm': 'uploadPdf'
            },
            onUploadComplete: function(file, data, response) {
                var result = $.parseJSON(data);
                if(result['status']==0) {
                    $('.js_pdf').val(result['name']);
                    $('.js_pdf_prev').attr('href', result['name']);
                    // $('.js_pdf_prev').html(result['name']);
                    $('.js_pdf_prev').html('[预览]');
                }
            },
            onError: function(errorType) {
                alert('The error was: ' + errorType);
            }
        });
        $('#js_upload_btn02').uploadifive({
            fileType: 'application/pdf',
            multi: false,
            removeCompleted: false,
            buttonText: '上传PDF',
            fileSizeLimit: '100MB',
            method: 'post',
            buttonClass: 'signup-upload-file',
            fileObjName: 'uploadfile',
            uploadScript: config.apiServer + 'pic_clazz/post',
            formData: {
                'actionxm': 'uploadPdf'
            },
            onUploadComplete: function(file, data, response) {
                var result = $.parseJSON(data);
                if(result['status']==0) {
                    $('.js_update_pdf').val(result['name']);
                    $('.js_pdf_update_prev').attr('href', result['name']);
                    // $('.js_pdf_prev').html(result['name']);
                    $('.js_pdf_update_prev').html('[预览]');
                }
            },
            onError: function(errorType) {
                alert('The error was: ' + errorType);
            }
        });
    })
</script>
