<link rel="stylesheet" href="<?php echo $resource_url; ?>css/uploadifive.css">
<link rel="stylesheet" href="<?php echo $resource_url; ?>libs/summernote/summernote.css">
<style media="screen">
.prev-pic {
    max-width: 400px;
    max-height: 300px;
    display: block;
    margin: 20px;
    border: 1px solid #ccc;
    padding: 10px;
}
.prev-frame {
    display: inline-block;
    position: relative;
}
.prev-frame em {
    position: absolute;
    right: 25px;
    top: 20px;
    background: red;
    display: inline-block;
    width: 20px;
    height: 20px;
    text-align: center;
    color: #fff;
    font-weight: 1000;
    cursor: pointer;
}

</style>
<div class="form-group">
    <label for="title">欄目標題（en）</label>
    <input type="text" disabled=disabled class="form-control" id="name_en" placeholder="请输入欄目標題（en）" value="<?php echo $info['name_en']; ?>">
</div>
<div class="form-group">
    <label for="title">欄目標題（tc）</label>
    <input type="text" disabled=disabled class="form-control" id="name_tc" placeholder="请输入欄目標題（tc）"  value="<?php echo $info['name_tc']; ?>">
</div>
<?php if ($nid==1):?>
    <div class="form-group">
    <label for="pic">首頁最新動態圖</label>
    <input id="pic" type="file" multiple="false" value="" />
    <div class="js_picPrevArea"></div>
    </div>
    <div class="form-group">
    <label for="descript_en">最新動態描述（en）</label>
    <textarea class="form-control" id="descript_en"><?php echo $info['descript_en']; ?></textarea>
    </div>
    <div class="form-group">
    <label for="descript_tc">首頁最新動態描述（tc）</label>
    <textarea class="form-control" id="descript_tc"><?php echo $info['descript_tc']; ?></textarea>
    </div>
<?php endif; ?>
<?php if ($nid==3||$nid==4):?>
    <div class="form-group">
    <label for="pic">首圖</label>
    <input id="pic" type="file" multiple="false" value="" />
    <div class="js_picPrevArea"></div>
    </div>
<?php endif; ?>
<div class="form-group">
    <label for="content_en">正文內容（en）</label>
    <div id="content_en"></div>
</div>
<div class="form-group">
    <label for="content_tc">正文內容（tc）</label>
    <div id="content_tc"></div>
</div>
<textarea class="js_pContent_en" style="display: none;"><?php echo $info['content_en']; ?></textarea>
<textarea class="js_pContent_tc" style="display: none;"><?php echo $info['content_tc']; ?></textarea>

<input type="hidden" name="nid" value="<?php echo $nid; ?>" class="js_nid">
<input type="hidden" class="js_update_pic" value='<?php echo $info['pic']; ?>'>

<button type="submit" class="btn btn-primary js_submit">保存</button>

<script src="<?php echo $resource_url; ?>js/jquery.uploadifive.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/summernote.js"></script>
<script src="<?php echo $resource_url; ?>libs/summernote/lang/summernote-zh-CN.js"></script>
<script src="<?php echo $resource_url; ?>js/system/static_update.js"></script>
<script type="text/javascript">
    $(function() {
        $('#content_en').summernote('code', $('.js_pContent_en').val());
        $('#content_tc').summernote('code', $('.js_pContent_tc').val());

    })
</script>
