    <script>
        var _hmt = _hmt || [];
        (function() {
            var hm = document.createElement("script");
            hm.src = "https://hm.baidu.com/hm.js?aa3c4c8b6ac9cc463974de338fbd1ec7";
            var s = document.getElementsByTagName("script")[0];
            s.parentNode.insertBefore(hm, s);
        })();
        console.log('Hi, I\'m Eric.');
        console.log('If you have any further questions and/or comments, please fee free to contact me at %clowkey361@gmail.com .', 'color:red');
    </script>

</body>
</html>
