<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title><?php echo $htmlTitle; ?></title>
    <meta name="author" content="Eric" />
    <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0;" name="viewport" />
    <link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>css/animate.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>css/bootstrap.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>css/reset.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>css/common.css">
    <link rel="stylesheet" type="text/css" href="<?php echo $resource_url; ?>css/index.css">

    <script type="text/javascript" src="<?php echo $resource_url; ?>js/jquery-3.2.0.js"></script>
    <script type="text/javascript" src="<?php echo $resource_url; ?>js/common.js"></script>
    <script type="text/javascript">
        window.base_url = "<?php echo $base_url; ?>";
    </script>
</head>
<body>
