                </div>
            </div>
        </div>

        <!-- Bootstrap core JavaScript
        ================================================== -->
        <script src="<?php echo $resource_url; ?>js/bootstrap.min.js"></script>
        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
        <script src="<?php echo $resource_url; ?>js/ie10-viewport-bug-workaround.js"></script>
    </body>
</html>
