  <div class="mid">
    <div class="bottom">
      <div class="locate wrap">
        <span class="content"><?=$navi5?> > <?=$subnavi6?></span>
      </div>
    </div>

    <div class="wrap">
      <div class="menu <?=$curLang?>">
        <div class="nav">
          <div class="tit">
            <?=$subnavi5?>
          </div>
          <div class="sub-nav" style="display: none">
              <?php if ($curLang === 'tc'): ?>
                <?php foreach ($submenu as $sub): ?>
                    <div class="sub-tit" data-id="<?=$sub['id']?>"><a href="<?=$home?>press_release?id=<?=$sub['id']?>"><?php echo $sub['name_tc']?></a></div>
                <?php endforeach; ?>
              <?php else: ?>
                <?php foreach ($submenu as $sub): ?>
                    <div class="sub-tit"><a href="<?=$home?>press_release?id=<?=$sub['id']?>"><?php echo $sub['name_en']?></a></div>
                <?php endforeach; ?>
              <?php endif; ?>
          </div>
        </div>
        <div class="nav cur">
          <div class="tit">
            <?=$subnavi6?>
          </div>
        </div>
      </div>
      <div class="container3 <?=$curLang?>">
        <?php if ($curLang === 'tc'): ?>
        <?php foreach ($searchNews as $new): ?>
          <div class="press item">
              <?php if ($new['cover_thumb']): ?>

                  <div class="pic">
                    <a href="<?=$home?>press_release/detail?id=<?=$new['id']?>">
                        <img src="<?php echo $new['cover_thumb'] ?>" alt="">
                    </a>
                  </div>
                <div class="detail" style="width:576px !important">
                  <div class="tit">
                      <a target="_blank" href="<?=$home?>web/getMedia?id=<?=$new['id']?>">
                          <?php echo $new['title_tc'] ?>
                      </a>
                  </div>
                  <div class="date">
                    <?php echo date('y-m-d',$new['create_time']) ?><span style="">&nbsp&nbsp|&nbsp&nbsp</span>
                  </div>
                  <div class="author">
                    <?php echo $new['author_tc'] ?>
                  </div>
                </div>
            <?php else: ?>
                <div class="detail">
                  <div class="tit2">
                      <a target="_blank" href="<?=$home?>web/getMedia?id=<?=$new['id']?>">
                          <?php echo $new['title_tc'] ?>
                      </a>
                  </div>
                  <div class="date">
                    <?php echo date('y-m-d',$new['create_time']) ?><span style="">&nbsp&nbsp|&nbsp&nbsp</span>
                  </div>
                  <div class="author">
                    <?php echo $new['author_tc'] ?>
                  </div>
                </div>
            <?php endif; ?>
          </div>
        <?php endforeach; ?>
        <?php else: ?>
          <?php foreach ($searchNews as $new): ?>
            <div class="press item" style="width:780px !important">
                <?php if ($new['cover_thumb']): ?>

                    <div class="pic">
                      <a href="<?=$home?>press_release/detail?id=<?=$new['id']?>">
                          <img src="<?php echo $new['cover_thumb'] ?>" alt="">
                      </a>
                    </div>
                  <div class="detail" style="width:476px !important">
                    <div class="tit">
                        <a target="_blank" href="<?=$home?>web/getMedia?id=<?=$new['id']?>">
                            <?php echo $new['title_en'] ?>
                        </a>
                    </div>
                    <div class="date">
                      <?php echo date('y-m-d',$new['create_time']) ?><span style="">&nbsp&nbsp|&nbsp&nbsp</span>
                    </div>
                    <div class="author">
                      <?php echo $new['author_en'] ?>
                    </div>
                  </div>
              <?php else: ?>
                  <div class="detail">
                    <div class="tit2">
                        <a target="_blank" href="<?=$home?>web/getMedia?id=<?=$new['id']?>">
                            <?php echo $new['title_en'] ?>
                        </a>
                    </div>
                    <div class="date">
                      <?php echo date('y-m-d',$new['create_time']) ?><span style="">&nbsp&nbsp|&nbsp&nbsp</span>
                    </div>
                    <div class="author">
                      <?php echo $new['author_en'] ?>
                    </div>
                  </div>
              <?php endif; ?>
            </div>
          <?php endforeach; ?>

        <?php endif; ?>
      </div>
    </div>


  </div>
<script src="<?php echo $resource_url; ?>js/press_media.js" charset="utf-8"></script>
