<div class="mid4 terms">
  <div class="bottom">
    <div class="locate wrap">
      <span class="content"><?=$terms?></span>
    </div>
  </div>
  <div class="wrap">
      <div class="container" style="border:0">
        <?php if ($curLang==='tc'): ?>
          <div class="tit">
            <?=$tandc->name_tc?>
          </div>
          <div class="contant">
            <?=$tandc->content_tc?>
          </div>
        <?php else: ?>
          <div class="tit">
            <?=$tandc->name_en?>
          </div>
          <div class="contant">
            <?=$tandc->content_en?>
          </div>
        <?php endif; ?>
      </div>
  </div>
</div>
<!-- <script src="<?php echo $resource_url; ?>js/swiper.min.js"></script> -->
<!-- <script src="<?php echo $resource_url; ?>js/catalogue_detail.js" charset="utf-8"></script> -->
