<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <!-- <meta name="viewport" content="width=640,initial-scale=0.3,maximum-scale=0.3,minimum-scale=0.3,user-scalable=no"> -->
  <meta name="viewport" content="width=640,initial-scale=0.3">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- <title><?=$title?></title>
  <meta property="og:title" content="<?=$title?>" />
  <meta property="og:description" content="<?=$og_description?>" />
  <meta name="keywords" content="仕宏拍賣, L & H Auction">
  <meta name="description" content="<?=$description?>"> -->
</head>
<body>
    <img src="<?=$press_media->pic;?>" alt="">
</body>
